version: '2' #Old school :P
services:
    # server:
    #     container_name: echo_server
    #     build: .
    #     working_dir: /ECHOProject
    #     command: ['/bin/bash', '-c', 'tail -f /dev/null']
    #     network_mode: host
    #     volumes:
    #         - .:/ECHOProject
    #         - /ECHOProject/node_modules
        # ports:
        #     - 3000:3000
        #     - 8888:8888

    db:
        container_name: echo_db
        image: 'mysql:5.7'
        #network_mode: host
        # volumes:
        #     #- /var/lib/mysql:/var/lib/mysql      # Must be empty for docker-entrypoint-initdb.d loading to work!
        #     - ./mysql:/docker-entrypoint-initdb.d # The mySQL image looks to this directory and runs any SQL found there
        environment:
            MYSQL_ROOT_PASSWORD: awfulPassword
            MYSQL_USER: dev
            MYSQL_PASSWORD: awfulPassword
            MYSQL_DATABASE: echo
        ports:
            - 3306:3306
