// UI Mutations:
export const TOGGLE_FLAG = 'TOGGLE_FLAG'

// User Mutations:
export const RECEIVED_CURRENT_USER = 'RECEIVED_CURRENT_USER'
export const UPDATED_USER_PASSWORD = 'UPDATED_USER_PASSWORD'
export const UPDATED_USER_PROFILE = 'UPDATED_USER_PROFILE'

export const UPDATE_ALL_CATEGORIES = 'UPDATE_ALL_CATEGORIES'
export const UPDATE_ALL_PERIODS = 'UPDATE_ALL_PERIODS'
export const UPDATE_ALL_SUBJECTS = 'UPDATE_ALL_SUBJECTS'
export const UPDATE_ALL_THEMES = 'UPDATE_ALL_THEMES'
export const UPDATE_ALL_LOCATIONS = 'UPDATE_ALL_LOCATIONS'
export const UPDATE_ALL_NAMES = 'UPDATE_ALL_NAMES'
export const UPDATE_ALL_STORIES = 'UPDATE_ALL_STORIES'
