<template>
    <div class="container">
        <div class="row">
            <h2 class="pageTitle">Add/Edit Stories</h2>
            <div class="activeStoryListContainer">
                <h6>Active Stories</h6>
                <ul class="selectAttributeList" id="selectStory">
                    <li v-for="story in this.storyList" v-on:click="selectStory(story.id)">
                        {{story.title}}
                    </li>
                </ul>
                <div class="formBtnContainer">
                    <button class="formBtn saveBtn" v-on:click="saveStory">Save</button>
                    <button class="formBtn clearBtn" v-on:click="clearStory" type="reset">Cancel</button>
                    <button class="formBtn delBtn" v-on:click="delStory">Delete</button>
                </div>
            </div>

            <form class="editAttributeForm" id="editStoryForm">
                <label class="editFormLbl" for="storyTitle">Story Title:</label>
                <input type="text" class="editFormTxt" id="storyName" v-model="selectedStory.title" placeholder="Story Title"/>

                <label class="editFormLbl" for="storyDesc">Story Description:</label>
                <textarea type="text" class="editFormTxtArea" id="storyDesc" v-model="selectedStory.description">Story Description</textarea>

                <label class="editFormLbl" for="storyAuthor">Story Author(s):</label>
                <span class="authorLines">
                    <span class="authorLine">
                        <input type="text" class="editFormTxt storyAuthor" placeholder="Author Name"/>
                        <input type="hidden" class="storyAuthorId" value=""/>
                    </span>
                </span>
                <span class="lineBtn addLineBtn" v-on:click="addAuthorLine">+</span>
                <span class="lineBtn delLineBtn" v-on:click="delAuthorLine">-</span>

                <span class="hasToolTip">
                    <label class="editFormLbl" for="youtubeId">YouTube ID:</label>
                    <input type="text" class="editFormTxt" id="youtubeId" v-model="selectedStory.youtubeId" placeholder="YouTube ID"/>
                </span>
                <span
                    class="toolTipAnchor"
                    v-on:mouseover="showToolTip('id', $event)"
                    v-on:mouseout="hideToolTip('id')"
                >i</span>
                <span id="idToolTip" class="toolTipPopup">
                    The YouTube ID is generated by YouTube when a video is initially uploaded.
                    This field will automatically be populated with the YouTube ID when a
                    video is done uploading, or you can manually enter the YouTube ID for a
                    video that has already been uploaded. The YouTube ID is most easily obtained
                    by looking at the URL for a video: https://www.youtube.com/watch?v=&lt;YouTube ID Here&gt;
                </span>

                <span class="hasToolTip">
                    <label class="editFormLbl" for="privacy-status">YouTube Privacy Status:</label>
                    <select class="editFormSel" id="privacy-status">
                        <option>Public</option>
                        <option>Unlisted</option>
                        <option>Private</option>
                    </select>
                </span>
                <span
                    class="toolTipAnchor"
                    v-on:mouseover="showToolTip('privacy', $event)"
                    v-on:mouseout="hideToolTip('privacy')"
                >i</span>
                <span id="privacyToolTip" class="toolTipPopup">
                    The YouTube Privacy Status setting controls the level of access
                    for both this site and users browsing on YouTube.<br/>
                    <ul>
                        <li>
                            <b>Public</b> means the video can be searched and found on YouTube,
                            and on this site.<br/>
                        </li>
                        <li>
                            <b>Unlisted</b> means that the video can be found on this site, but will
                            not be searchable on YouTube. The video will be viewable on YouTube if
                            the user has a direct link to it.<br/>
                        </li>
                        <li>
                            <b>Private</b> means the video will not be available on this site or on
                            YouTube.
                        </li>
                    </ul>
                    Once set, this setting can be changed directly from the YouTube account. In
                    general, this should be set to <b>Public</b> in order for the video to get
                    the most visibility.
                </span>
                <br/>
                <span class="hasToolTip cbHasToolTip">
                    <label class="editFormCheckLbl" for="approved">Visible on This Site:</label>
                    <input type="checkbox" class="editFormCheck" v-model="selectedStory.approved" id="approved" />
                </span>
                <span
                    class="toolTipAnchor"
                    v-on:mouseover="showToolTip('visibility', $event)"
                    v-on:mouseout="hideToolTip('visibility')"
                >i</span>
                <span id="visibilityToolTip" class="toolTipPopup">
                    This setting controls whether or not a given story will be visible on this site
                    specifically; the story will not appear in tag searches, keyword searches, or in
                    the featured story rotation if it is not visible. This setting has no bearing on
                    the settings for the video on YouTube. To change the visibility of the video on
                    YouTube, it must be edited from YouTube directly.
                </span>

                <br/>
                <label class="editFormCheckLbl" for="featuredRotation">Featured Rotation:</label>
                <input type="checkbox" class="editFormCheck" v-model="selectedStory.featuredRotation" id="featuredRotation" />

                <label class="editFormLbl" for="storagePath">Upload Video:</label>
                <div class="uploadVideoContainer">

                    <span id="signinButton" class="pre-sign-in">
                        <span
                            class="g-signin"
                            data-callback="signinCallback"
                            data-clientid="261927204966-ttg4vjb3k1d8opg12ol8fl6n57o04od7.apps.googleusercontent.com"
                            data-cookiepolicy="single_host_origin"
                            data-scope="https://www.googleapis.com/auth/youtube.upload https://www.googleapis.com/auth/youtube"
                        >
                        </span>
                    </span>

                    <div class="post-sign-in">
                        <div class="channel-info">
                            <img class="channelThumb" id="channel-thumbnail">
                            <span class="channelName" id="channel-name"></span>
                        </div>

                        <div>
                            <input input type="file" id="file" class="uploadBtn" accept="video/*">
                            <button class="formBtn saveBtn" id="upload-button">Upload Video</button>
                        </div>

                        <div class="during-upload">
                            <label class="editFormLbl" for="percent-transferred">Upload Progress:</label>
                            <p>
                                <span id="percent-transferred"></span>% done<br/>
                                (<span id="bytes-transferred"></span>/<span id="total-bytes"></span> bytes)
                            </p>
                            <progress id="upload-progress" max="1" value="0"></progress>
                        </div>

                        <div class="post-upload">
                            <label class="editFormLbl" for="video-id">Upload Complete:</label>
                            <p>Uploaded video with ID <span id="video-id"></span>. Polling for status...</p>
                            <ul id="post-upload-status"></ul>
                            <div id="player"></div>
                        </div>
                        <p id="disclaimer">
                            By uploading a video, you certify that you own all rights to the content
                            or that you are authorized by the owner to make the content publicly
                            available on YouTube, and that it otherwise complies with the YouTube
                            Terms of Service located at
                            <a href="http://www.youtube.com/t/terms" target="_blank">http://www.youtube.com/t/terms</a>
                        </p>
                    </div>
                </div>

                <input type="hidden" id="uploadInProgress" v-model="uploadInProgress"/>
                <input type="hidden" id="storyId" v-model="selectedStory.id"/>
            </form>

            <div class="attributeListContainer">
                <h3>Select Story Tags</h3>
                <div class="editStoryAttributeColumn">
                    <span>Subjects:</span>
                    <ul class="selectStoryAttributeList" id="selectSubject">
                        <li v-for="subject in this.subjectList" :id="'subjects' + subject.id" v-on:click="toggleSel('subjects', subject.id)">
                            &bull; {{subject.name}}
                        </li>
                    </ul>
                </div>
                <div class="editStoryAttributeColumn">
                    <span>Categories:</span>
                    <ul class="selectStoryAttributeList" id="selectCategory">
                        <li v-for="category in this.categoryList" :id="'categories' + category.id" v-on:click="toggleSel('categories', category.id)">
                            &bull; {{category.name}}
                        </li>
                    </ul>
                </div>
                <div class="editStoryAttributeColumn">
                    <span>Names:</span>
                    <ul class="selectStoryAttributeList" id="selectName">
                        <li v-for="name in this.nameList" :id="'names' + name.id" v-on:click="toggleSel('names', name.id)">
                            &bull; {{name.name}}
                        </li>
                    </ul>
                </div>
                <div class="editStoryAttributeColumn">
                    <span>Dates:</span>
                    <ul class="selectStoryAttributeList" id="selectPeriod">
                        <li v-for="period in this.periodList" :id="'periods' + period.id" v-on:click="toggleSel('periods', period.id)">
                            &bull; {{period.name}}
                        </li>
                    </ul>
                </div>
                <div class="editStoryAttributeColumn">
                    <span>Locations:</span>
                    <ul class="selectStoryAttributeList" id="selectLocation">
                        <li v-for="location in this.locationList" :id="'locations' + location.id" v-on:click="toggleSel('locations', location.id)">
                            &bull; {{location.name}}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</template>
<script>
import { mapActions, mapGetters } from 'vuex'
import moment from 'moment'

export default {
  components: {},

  data: () => ({
    storyList: null,
    categoryList: null,
    periodList: null,
    locationList: null,
    subjectList: null,
    nameList: null,
    selectedStory: {
      id: null,
      title: null,
      description: null,
      approved: null,
      youtubeId: '',
      publishDate: '',
      categories: [],
      locations: [],
      names: [],
      periods: [],
      subjects: [],
      authors: [],
      featuredRotation: null
    },
    selectedCategories: [],
    selectedPeriods: [],
    selectedLocations: [],
    selectedSubjects: [],
    selectedNames: [],
    selectedAuthors: [],
    uploadInProgress: 0
  }),

  created () {
    // this.fetchData()
  },

  mounted () {
    this.fetchData()
  },

  computed: Object.assign(
    mapGetters([
      'allStories',
      'allCategories',
      'allLocations',
      'allNames',
      'allPeriods',
      'allSubjects'
    ])
  ),

  methods: Object.assign({
    fetchData () {
      this.getAllStories()
        .then(() => {
          this.storyList = this.allStories
        })

      this.getAllPeriods()
        .then(() => {
          this.periodList = this.allPeriods
        })

      this.getAllCategories()
        .then(() => {
          this.categoryList = this.allCategories
        })

      this.getAllSubjects()
        .then(() => {
          this.subjectList = this.allSubjects
        })

      this.getAllNames()
        .then(() => {
          this.nameList = this.allNames
        })

      this.getAllLocations()
        .then(() => {
          this.locationList = this.allLocations
        })

      this.clearForm()
    },

    selectStory (storyId) {
      if (!this.checkInterruptUpload()) { return }
      this.clearForm()

      this.adminGetStoryById(storyId)
        .then((result) => {
          this.selectedStory.id = result.id
          this.selectedStory.title = result.title
          this.selectedStory.description = result.description
          this.selectedStory.youtubeId = result.youtube_path
          this.selectedStory.featuredRotation = result.featured_rotation > 0
          this.selectedStory.approved = result.approved > 0

          this.selectedStory.categories = result.categories
          this.selectedStory.periods = result.periods
          this.selectedStory.subjects = result.subjects
          this.selectedStory.locations = result.locations
          this.selectedStory.names = result.names
          this.selectedStory.authors = result.authors
          this.selectedStory.publishDate = result.publish_date

          for (var category of this.selectedStory.categories) { this.toggleSel('categories', category) }
          for (var period of this.selectedStory.periods) { this.toggleSel('periods', period) }
          for (var subject of this.selectedStory.subjects) { this.toggleSel('subjects', subject) }
          for (var location of this.selectedStory.locations) { this.toggleSel('locations', location) }
          for (var name of this.selectedStory.names) { this.toggleSel('names', name) }

          if (this.selectedStory.authors.length > 0) {
            $('.authorLine:first').find('.storyAuthor').val(this.selectedStory.authors[0].name)
            $('.authorLine:first').find('.storyAuthorId').val(this.selectedStory.authors[0].id)
            for (var i = 1; i < this.selectedStory.authors.length; i++) {
              this.addAuthorLine()
              $('.authorLine:last').find('.storyAuthor').val(this.selectedStory.authors[i].name)
              $('.authorLine:last').find('.storyAuthorId').val(this.selectedStory.authors[i].id)
            }
          }
        })
    },

    saveStory () {
      if (!this.checkInterruptUpload()) { return }

      if (!this.selectedStory.title || this.selectedStory.title == '' || !this.selectedStory.description || this.selectedStory.description == '') {
        alert('Some fields were left blank. Please check the form and try again.')
        return
      }

      var authors = []
      $('.authorLines .authorLine').each(function () {
        var authorName = $(this).find('.storyAuthor').val()
        if (authorName && authorName != '') {
          authors.push({
            id: $(this).find('.storyAuthorId').val(),
            name: authorName
          })
        }
      })

      if (authors.length < 1) {
        alert('No authors were added. Please check the form and try again.')
        return
      }

      if ($('#youtubeId').val() && $('#youtubeId').val() != '' && $('#youtubeId').val() != this.selectedStory.youtubeId) {
        this.selectedStory.youtubeId = $('#youtubeId').val()
      }

      this.selectedStory.categories = this.selectedCategories
      this.selectedStory.periods = this.selectedPeriods
      this.selectedStory.locations = this.selectedLocations
      this.selectedStory.subjects = this.selectedSubjects
      this.selectedStory.names = this.selectedNames
      this.selectedStory.authors = authors

      if (this.selectedStory.approved) {
        if (this.selectedStory.publishDate == '' || !this.selectedStory.publishDate) {
          this.selectedStory.publishDate = moment().format('YYYY-MM-DD HH:mm:ss')
        }
      }

      if (this.selectedStory.id === null || this.selectedStory.id === '' || this.selectedStory.id === 0) {
        this.createStory(this.selectedStory)
          .then((result) => {
            this.fetchData()
            alert('Story created.')
          })
      } else {
        this.updateStory(this.selectedStory)
          .then((result) => {
            this.fetchData()
            alert('Story saved.')
          })
      }
    },

    delStory () {
      if (!this.checkInterruptUpload()) { return }

      if (this.selectedStory.id === null || this.selectedStory.id === '' || this.selectedStory.id === 0) {
        return
      }

      if (!confirm('This will permanently remove the selected story from the system. Proceed?')) {
        return
      }

      this.deleteStory(this.selectedStory.id)
        .then((result) => {
          this.fetchData()
          alert('Story deleted.')
        })
    },

    clearStory () {
      if (!this.checkInterruptUpload()) { return }
      this.clearForm()
    },

    clearForm () {
      this.selectedStory.id = null
      this.selectedStory.title = null
      this.selectedStory.description = null
      this.selectedStory.approved = null
      this.selectedStory.featuredRotation = null
      this.selectedStory.youtubeId = ''
      this.clearTags()
      this.clearAuthors()
    },

    toggleSel (type, id) {
      var dataType = type.charAt(0).toUpperCase() + type.substr(1).toLowerCase()
      var idIndex = this['selected' + dataType].indexOf(id)

      if (idIndex >= 0) {
        this['selected' + dataType].splice(idIndex, 1)
        $('#' + type + id).removeClass('selectedAttribute')
      } else {
        this['selected' + dataType].push(id)
        $('#' + type + id).addClass('selectedAttribute')
      }
    },

    addAuthorLine () {
      $('.authorLines').append(
        '<span class="authorLine">' +
        '<input type="text" class="editFormTxt storyAuthor" placeholder="Author Name"/>' +
        '<input type="hidden" class="storyAuthorId" value=""/>' +
        '</span>'
      )
      var lineLen = $('.authorLines .authorLine').length
      if (lineLen > 1) { $('.delLineBtn').css({'display': 'inline-block'}) }
    },

    delAuthorLine () {
      $('.authorLines .authorLine').last().remove()
      var lineLen = $('.authorLines .authorLine').length
      if (lineLen === 1) { $('.delLineBtn').css({'display': 'none'}) }
    },

    clearTags () {
      this.selectedCategories = []
      this.selectedPeriods = []
      this.selectedLocations = []
      this.selectedSubjects = []
      this.selectedNames = []

      $('.selectedAttribute').each(function () {
        $(this).removeClass('selectedAttribute')
      })
    },

    clearAuthors () {
      $('.authorLines .authorLine').not(':first').remove()
      $('.delLineBtn').css({'display': 'none'})
      $('.storyAuthor').val('')
    },

    showToolTip (ttName, event) {
      var relX = event.target.offsetLeft + 30
      var relY = event.target.offsetTop

      $('#' + ttName + 'ToolTip').css({
        'display': 'block',
        'top': relY,
        'left': relX
      })
    },

    hideToolTip (ttName) {
      $('#' + ttName + 'ToolTip').css({
        'display': 'none'
      })
    },

    checkInterruptUpload () {
      if (($('#uploadInProgress').val() && $('#uploadInProgress').val() != 0) || this.uploadInProgress != 0) {
        if (!confirm('Upload is currently in progress. This might interfere with the upload process. Continue?')) {
          return false
        }
      }
      return true
    }
  }, mapActions([
    'getStoryById',
    'adminGetStoryById',
    'getAllStories',
    'getAllCategories',
    'getCategoryById',
    'getAllPeriods',
    'getPeriodById',
    'getAllNames',
    'getNameById',
    'getAllLocations',
    'getLocationById',
    'getAllSubjects',
    'getSubjectById',
    'updateStory',
    'addNewStory',
    'createStory',
    'deleteStory'
  ]))
}
</script>
